Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - 'db/**/*'
  - 'bin/**/*'
  - 'lib/tasks/**/*'

